"""add foreign key to Review

Revision ID: 4ae93569db86
Revises: 02cb1e5bbe1c
Create Date: 2025-06-16 08:20:00.241868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae93569db86'
down_revision = '02cb1e5bbe1c'
branch_labels = None
depends_on = None


def upgrade():
    # Use batch mode to safely modify the table in SQLite
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk_reviews_employee_id_employees'),
            'employees',
            ['employee_id'],
            ['id']
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
